const godList = [
    "AH MUZEN CAB",
    "AH PUCH",
    "AMATERASU",
    "AHNUR",
    "ANUBIS",
    "AO KUANG",
    "APHRODITE",
    "APOLLO",
    "ARACHNE",
    "ARES",
    "ARTEMIS",
    "ARTIO",
    "ATHENA",
    "AWILIX",
    "BACCHUS",
    "BAKASURA",
    "BARON SAMEDI",
    "BASTET",
    "BELLONA",
    "CABRAKAN",
    "CAMAZOTZ",
    "CERBERUS",
    "Cernunnos",
    "CHAAC",
    "CHENG'E",
    "CHERNOBOG",
    "CHIRON",
    "CHRONOS",
    "CU CHULAINN",
    "CUPID",
    "DA JI",
    "DISCORDIA",
    "ERLANG SHEN",
    "FAFNIR",
    "FENRIR",
    "Freya ",
    "GANESHA",
    "GEB",
    "GUAN YU",
    "HACHIMAN",
    "HADES",
    "HE BO",
    "HEL",
    "HERA",
    "HERCULES",
    "HORUS",
    "HOU YI",
    "HUN BATZ",
    "ISIS",
    "IZANAMI",
    "JANUS",
    "JING WEI",
    "JORMUNGANDR ",
    "KALI",
    "KHEPRY",
    "KING ARTHUR",
    "KUKULKAN",
    "KUMBHAKARNA",
    "KUZENBO",
    "LOKI",
    "MEDUSA",
    "MERCURY",
    "MERLIN",
    "NE ZHA",
    "NEITH",
    "NEMESIS",
    "NIKE",
    "NOX",
    "NU WA",
    "ODIN",
    "OSIRIS",
    "PELE",
    "POSEIDON",
    "RA",
    "RAIJIN",
    "RAMA",
    "RATATOSKR",
    "RAVANA",
    "SCYLLA",
    "SERQET",
    "SET",
    "SKADI",
    "SOBEK",
    "SOL",
    "SUN WUKONG",
    "SUSANO",
    "SYLVANUS",
    "TERRA",
    "THANATOS",
    "THE MORRIGAN",
    "THOR",
    "THOTH",
    "TYR",
    "ULLR",
    "VAMANA",
    "VULCAN",
    "XBALANQUE",
    "XING TIAN",
    "YMIR",
    "ZEUS",
    "ZHONG KUI"
]

module.exports = godList[Math.floor(Math.random()*godList.length)]